// Generated by CoffeeScript 1.8.0
(function() {
  var app, encounters, express, records, server;
  express = require("express");
  var bodyParser = require('body-parser');
  var exchangeAPI =require ("./lib/api");
  var dao =require ("./lib/dao");
	function errorHandler(err, req, res, next) {
	  if (res.headersSent) {
		return next(err);
	  }
	  res.status(500);
	  res.render('error', { error: err });
	}
  app = express();
  app.use(bodyParser.json());
  app.use(bodyParser.urlencoded());
  //app.use(express.static(entityAPI.resolvePathDirectory(__dirname,'public')));
  app.use(errorHandler);server = app.listen(process.env.PORT || 8084, function() {
    return console.log("SMS2Sparrow exchange is running on port:" + (server.address().port));
  });
  
	function sendSMS(from,text,to,id,res)
	{
		exchangeAPI.SendSMS(from,text,to,id,function(resAPI)
		{
			//console.log("Send report: "+resAPI);
			//res.json(resAPI);
			//console.log(resAPI[0].status);
			//return res.end();
			if(resAPI[0].response_code==200)
			{
				console.log("Messages sent");
				res.json('{"response":"Messages sent"}');
				//Log the sms in the db
				dao.saveSMS(id,from,to,function(resBD)
				{
					if(resBD==true)
					{
						console.log("Success: SMS logged in the DB");
					}
					else
					{
						console.log("Fail: SMS not logged in the DB");
					}
					return res.end();
				});
				
				
				
			}
		});
	}
	function sendAndNotify(from,text,to,id,res)
	{
		exchangeAPI.SendSMSAndNotifySuccess(from,text,to,id,function(resAPI)
		{
			console.log(resAPI[0]);
			res.json(resAPI[0]);
			res.end();
		});
		
	}
	function reportSentToRapidPro(res)
	{
		dao.getListSMS3(function(listSMS)
		{
			if(listSMS!=null)
			{
				var oSMS=listSMS;
				exchangeAPI.notifySendSucceded(oSMS.id,function(resRP)
				{
					//console.log(resRP[0]);
					if(resRP[0].response=="SMS Status Updated")
					{
						dao.editSMS(oSMS.id,1,function (resSB)
						{
							if(resSB==true)
							{
								console.log("Success "+oSMS.id+": SMS updated in the DB")
								//res.js('{"Success":"SMS updated in the DB"}');
							}
							else
							{
								console.log("Fail: SMS not updated in the DB");
								//res.send('{"Fail":"SMS not updated in the DB"}');
							}
							res.json('{"response":"message updated in rapidPro"}');
							return res.end();
						});
					}
					else
					{
						
					}
					
				});
			}
			else
			{
				res.json('{"response":"No messages in pending"}');
				return res.end();
			}
			
		});
		
	}
	function reportSentToRapidPro2(res)
	{
		dao.getListSMS2();
		
	}
	
	app.param ("from", function (req,res,next,from)
	{
		req.from=from;
		next();
	});
	app.param ("text", function (req,res,next,text)
	{
		req.text=text;
		next();
	});
	app.param ("to", function (req,res,next,to)
	{
		req.to=to;
		next();
	});
	app.param ("id", function (req,res,next,id)
	{
		req.id=id;
		next();
	});
	app.get ("/send/from=:from&text=:text&to=:to&id=:id", function (req,res,next)
	{
		/*
		console.log("From:"+req.from);
		console.log("Text:"+req.text);
		console.log("To:"+req.to);
		console.log("To:"+req.id);
		* */
		
		sendSMS(req.from,req.text,req.to,req.id,res);
		
	});
	app.get ("/reportsent", function (req,res,next)
	{
		
		//reportSentToRapidPro(res);
		reportSentToRapidPro(res);
		
	});
	app.get ("/getsms", function (req,res,next)
	{
		
		//reportSentToRapidPro(res);
		//reportSentToRapidPro(res);
		console.log("Campain logged!!!!");
		console.log("----------------- >>>");
		console.log(req);
		res.json('{"response":"callback url called"}');
		return res.end();
		
	});

}).call(this);
